name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - main
    - feature/*
    


  paths:
    exclude:
      - doc
      - ReadME.md

pr:
  branches:
    include:
      - main

variables:
  - name: vmImage
    value: "windows-latest"
    # Azure Resource Manager connection created during pipeline creation
  - name: azureResourceManagerConnection
    value: "8d0e5f8f-2aa6-4d3a-9367-74ff7052856a"

stages:
  - stage: Build
    jobs:
      - job: "Build"
        pool:
          name: Default
        steps:
          - template: "build.yaml"
            parameters:
              projectFiles: "**/*.csproj"

  - stage: DEV
    dependsOn: ["Build"]
    jobs:
      - deployment: DEV
        variables:
          - template: "Variables/common.yaml"
          - template: "Variables/dev.yaml"
        pool:
          #vmImage: ${{variables.vmImage}}
          name: Default
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - template: "deploy.yaml"
                  parameters:
                    buildNumber: $(Build.BuildNumber)

  - stage: PRD
    dependsOn: ["DEV"]
    jobs:
      - deployment: PRD
        variables:
          - template: "Variables/common.yaml"
          - template: "Variables/prd.yaml"
        pool:
          #vmImage: ${{variables.vmImage}}
          name: Default
        environment: PRD
        strategy:
          runOnce:
            deploy:
              steps:
                - template: "deploy.yaml"
                  parameters:
                    buildNumber: $(Build.BuildNumber)